name: Build & Publish Release APK

on:
  push:
    branches:
      - develop
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Gradle:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Create Google Services JSON File
        env:
          # Stored as repo secret coded as base64
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./pokedex/google-services.json

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Decode Keystore
        run: |
          echo ${{ secrets.SIGNING_KEY }} > keystore-b64.txt
          base64 -d keystore-b64.txt > pokedex/${{ secrets.SIGNING_KEY_STORE_PATH }}

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release apk
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: |
          ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1 # Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pokedex/build/outputs/apk/release/pokedex-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive